service: blog-nest-server

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-prune-plugin
  - serverless-offline

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs18.x

functions:
  main:
    handler: src/main.runLambda
    events:
      - http:
          method: any
          path: /{any+}
