version: '3.7'

services:
  nginx:
    container_name: blog-nginx
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
#    volumes:
#      - ../config/nginx.conf:/etc/nginx/nginx.conf
#      - /docker-volumns/etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN_URL=begin0dev.me
      - CLIENT_URL=localhost:3000
    restart: 'unless-stopped'
