name: Node.js DEPLOY

on:
  push:
    branches: [master]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SETUP Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: INSTALL package.json
        run: npm ci

      - name: RUN test
        run: npm test

      - name: SETUP .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_PORT: 3001
          envkey_NODE_ENV: production
          envkey_CLIENT_URI: https://localhost:3000
          envkey_MONGO_URI: ${{ secrets.MONGO_URI }}
          envkey_MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          envkey_MONGO_USER: ${{ secrets.MONGO_USER }}
          envkey_MONGO_PWD: ${{ secrets.MONGO_PWD }}
          envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
          envkey_COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          envkey_FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          envkey_FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          envkey_KAKAO_APP_ID: ${{ secrets.KAKAO_APP_ID }}
          envkey_KAKAO_APP_SECRET: ${{ secrets.KAKAO_APP_SECRET }}
          file_name: .env

      - name: RUN npm build
        run: npm run build

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - name: LOGIN to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: BUILD and PUSH docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          push: true
          tags: begin0dev/blog-server:latest
